spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/INVENTORY-SERVICE?createDatabaseIfNotExist=true
    username: root
    password: Sonu#2000
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
      
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}


      


