spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/INVENTORY-SERVICE?createDatabaseIfNotExist=true
    username: root
    password: Sonu#2000
  jpa:
    hibernate:
      ddl-auto: create-drop
      
server:
  port: 8082
      

