spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ORDER-SERVICE?createDatabaseIfNotExist=true
    username: root
    password: Sonu#2000
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service




  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8081



