server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: PRODUCT-SERVICE
  application:
    name: product-service
  cloud:
    compatibility-verifier:
      enabled: false
