server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: PRODUCT-SERVICE
  application:
    name: product-service
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/dashboard